apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: mongodb-svc
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
